name: toy-ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install RTIMUlib
      run: |
        git clone https://github.com/RPi-Distro/RTIMULib
        python3 ./RTIMULib/Linux/python/setup.py build
        python3 ./RTIMULib/Linux/python/setup.py install
        rm -rf ./RTIMULib
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=W0511,C0116